// GENERATED by scripts/gen-abis.mjs from contracts/out/ChainlinkRateSource.sol/ChainlinkRateSource.json — do not edit.
export const chainlinkRateSourceAbi = [
  {
    "type": "constructor",
    "inputs": [
      {
        "name": "pairs",
        "type": "tuple[]",
        "internalType": "struct ChainlinkRateSource.FeedPair[]",
        "components": [
          {
            "name": "sourceAsset",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "targetAsset",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "base",
            "type": "address",
            "internalType": "contract AggregatorV3Interface"
          },
          {
            "name": "quote",
            "type": "address",
            "internalType": "contract AggregatorV3Interface"
          },
          {
            "name": "baseMaxAge",
            "type": "uint32",
            "internalType": "uint32"
          },
          {
            "name": "quoteMaxAge",
            "type": "uint32",
            "internalType": "uint32"
          }
        ]
      }
    ],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "RATE_DECIMALS",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint8",
        "internalType": "uint8"
      }
    ],
    "stateMutability": "pure"
  },
  {
    "type": "function",
    "name": "feeds",
    "inputs": [
      {
        "name": "sourceAsset",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "targetAsset",
        "type": "address",
        "internalType": "address"
      }
    ],
    "outputs": [
      {
        "name": "pair",
        "type": "tuple",
        "internalType": "struct ChainlinkRateSource.FeedPair",
        "components": [
          {
            "name": "sourceAsset",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "targetAsset",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "base",
            "type": "address",
            "internalType": "contract AggregatorV3Interface"
          },
          {
            "name": "quote",
            "type": "address",
            "internalType": "contract AggregatorV3Interface"
          },
          {
            "name": "baseMaxAge",
            "type": "uint32",
            "internalType": "uint32"
          },
          {
            "name": "quoteMaxAge",
            "type": "uint32",
            "internalType": "uint32"
          }
        ]
      },
      {
        "name": "baseDecimals",
        "type": "uint8",
        "internalType": "uint8"
      },
      {
        "name": "quoteDecimals",
        "type": "uint8",
        "internalType": "uint8"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "getRate",
    "inputs": [
      {
        "name": "sourceAsset",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "targetAsset",
        "type": "address",
        "internalType": "address"
      }
    ],
    "outputs": [
      {
        "name": "rate",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "updatedAt",
        "type": "uint64",
        "internalType": "uint64"
      },
      {
        "name": "observation",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "isSupported",
    "inputs": [
      {
        "name": "sourceAsset",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "targetAsset",
        "type": "address",
        "internalType": "address"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "bool",
        "internalType": "bool"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "name",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "string",
        "internalType": "string"
      }
    ],
    "stateMutability": "pure"
  },
  {
    "type": "error",
    "name": "DuplicatePair",
    "inputs": [
      {
        "name": "sourceAsset",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "targetAsset",
        "type": "address",
        "internalType": "address"
      }
    ]
  },
  {
    "type": "error",
    "name": "InvalidReferenceAnswer",
    "inputs": [
      {
        "name": "feed",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "answer",
        "type": "int256",
        "internalType": "int256"
      }
    ]
  },
  {
    "type": "error",
    "name": "StaleReferenceRate",
    "inputs": [
      {
        "name": "feed",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "updatedAt",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "maxAge",
        "type": "uint256",
        "internalType": "uint256"
      }
    ]
  },
  {
    "type": "error",
    "name": "UnsupportedFeedDecimals",
    "inputs": [
      {
        "name": "feed",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "decimals",
        "type": "uint8",
        "internalType": "uint8"
      }
    ]
  },
  {
    "type": "error",
    "name": "UnsupportedPair",
    "inputs": [
      {
        "name": "sourceAsset",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "targetAsset",
        "type": "address",
        "internalType": "address"
      }
    ]
  },
  {
    "type": "error",
    "name": "ZeroAddress",
    "inputs": []
  },
  {
    "type": "error",
    "name": "ZeroMaxAge",
    "inputs": [
      {
        "name": "feed",
        "type": "address",
        "internalType": "address"
      }
    ]
  }
] as const
