// GENERATED by scripts/gen-abis.mjs from contracts/out/CorridorRouter.sol/CorridorRouter.json — do not edit.
export const corridorRouterAbi = [
  {
    "type": "constructor",
    "inputs": [
      {
        "name": "owner_",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "attestation_",
        "type": "address",
        "internalType": "contract IRateAttestation"
      }
    ],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "INTENT_TYPEHASH",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "acceptOwnership",
    "inputs": [],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "attestation",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "contract IRateAttestation"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "cancel",
    "inputs": [
      {
        "name": "intent",
        "type": "tuple",
        "internalType": "struct PayoutIntent.Intent",
        "components": [
          {
            "name": "payer",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "recipient",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "sourceAsset",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "targetAsset",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "sourceAmount",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "quotedAmountOut",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "toleranceBps",
            "type": "uint16",
            "internalType": "uint16"
          },
          {
            "name": "maxSpreadBps",
            "type": "uint16",
            "internalType": "uint16"
          },
          {
            "name": "deadline",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "salt",
            "type": "bytes32",
            "internalType": "bytes32"
          }
        ]
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "corridors",
    "inputs": [
      {
        "name": "sourceAsset",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "targetAsset",
        "type": "address",
        "internalType": "address"
      }
    ],
    "outputs": [
      {
        "name": "corridor",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "rateSource",
        "type": "address",
        "internalType": "contract IRateSource"
      },
      {
        "name": "venue",
        "type": "address",
        "internalType": "contract IVenueAdapter"
      },
      {
        "name": "sourceDecimals",
        "type": "uint8",
        "internalType": "uint8"
      },
      {
        "name": "targetDecimals",
        "type": "uint8",
        "internalType": "uint8"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "eip712Domain",
    "inputs": [],
    "outputs": [
      {
        "name": "fields",
        "type": "bytes1",
        "internalType": "bytes1"
      },
      {
        "name": "name",
        "type": "string",
        "internalType": "string"
      },
      {
        "name": "version",
        "type": "string",
        "internalType": "string"
      },
      {
        "name": "chainId",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "verifyingContract",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "salt",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "extensions",
        "type": "uint256[]",
        "internalType": "uint256[]"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "hashIntent",
    "inputs": [
      {
        "name": "intent",
        "type": "tuple",
        "internalType": "struct PayoutIntent.Intent",
        "components": [
          {
            "name": "payer",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "recipient",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "sourceAsset",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "targetAsset",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "sourceAmount",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "quotedAmountOut",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "toleranceBps",
            "type": "uint16",
            "internalType": "uint16"
          },
          {
            "name": "maxSpreadBps",
            "type": "uint16",
            "internalType": "uint16"
          },
          {
            "name": "deadline",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "salt",
            "type": "bytes32",
            "internalType": "bytes32"
          }
        ]
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "intentStatus",
    "inputs": [
      {
        "name": "intentId",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "uint8",
        "internalType": "enum PayoutIntent.Status"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "minAmountOut",
    "inputs": [
      {
        "name": "intent",
        "type": "tuple",
        "internalType": "struct PayoutIntent.Intent",
        "components": [
          {
            "name": "payer",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "recipient",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "sourceAsset",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "targetAsset",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "sourceAmount",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "quotedAmountOut",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "toleranceBps",
            "type": "uint16",
            "internalType": "uint16"
          },
          {
            "name": "maxSpreadBps",
            "type": "uint16",
            "internalType": "uint16"
          },
          {
            "name": "deadline",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "salt",
            "type": "bytes32",
            "internalType": "bytes32"
          }
        ]
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "stateMutability": "pure"
  },
  {
    "type": "function",
    "name": "owner",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "address"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "pendingOwner",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "address"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "previewQuote",
    "inputs": [
      {
        "name": "sourceAsset",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "targetAsset",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "amountIn",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "outputs": [
      {
        "name": "quotedOut",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "referenceRate",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "status",
        "type": "uint8",
        "internalType": "enum IVenueAdapter.Status"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "registerCorridor",
    "inputs": [
      {
        "name": "sourceAsset",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "targetAsset",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "corridor",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "rateSource",
        "type": "address",
        "internalType": "contract IRateSource"
      },
      {
        "name": "venue",
        "type": "address",
        "internalType": "contract IVenueAdapter"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "renounceOwnership",
    "inputs": [],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "repointCorridor",
    "inputs": [
      {
        "name": "sourceAsset",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "targetAsset",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "rateSource",
        "type": "address",
        "internalType": "contract IRateSource"
      },
      {
        "name": "venue",
        "type": "address",
        "internalType": "contract IVenueAdapter"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "settle",
    "inputs": [
      {
        "name": "intent",
        "type": "tuple",
        "internalType": "struct PayoutIntent.Intent",
        "components": [
          {
            "name": "payer",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "recipient",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "sourceAsset",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "targetAsset",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "sourceAmount",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "quotedAmountOut",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "toleranceBps",
            "type": "uint16",
            "internalType": "uint16"
          },
          {
            "name": "maxSpreadBps",
            "type": "uint16",
            "internalType": "uint16"
          },
          {
            "name": "deadline",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "salt",
            "type": "bytes32",
            "internalType": "bytes32"
          }
        ]
      }
    ],
    "outputs": [
      {
        "name": "delivered",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "settleWithAuthorization",
    "inputs": [
      {
        "name": "intent",
        "type": "tuple",
        "internalType": "struct PayoutIntent.Intent",
        "components": [
          {
            "name": "payer",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "recipient",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "sourceAsset",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "targetAsset",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "sourceAmount",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "quotedAmountOut",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "toleranceBps",
            "type": "uint16",
            "internalType": "uint16"
          },
          {
            "name": "maxSpreadBps",
            "type": "uint16",
            "internalType": "uint16"
          },
          {
            "name": "deadline",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "salt",
            "type": "bytes32",
            "internalType": "bytes32"
          }
        ]
      },
      {
        "name": "signature",
        "type": "bytes",
        "internalType": "bytes"
      }
    ],
    "outputs": [
      {
        "name": "delivered",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "transferOwnership",
    "inputs": [
      {
        "name": "newOwner",
        "type": "address",
        "internalType": "address"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "event",
    "name": "CorridorRegistered",
    "inputs": [
      {
        "name": "sourceAsset",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "targetAsset",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "corridor",
        "type": "bytes32",
        "indexed": true,
        "internalType": "bytes32"
      },
      {
        "name": "rateSource",
        "type": "address",
        "indexed": false,
        "internalType": "address"
      },
      {
        "name": "venue",
        "type": "address",
        "indexed": false,
        "internalType": "address"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "CorridorRepointed",
    "inputs": [
      {
        "name": "sourceAsset",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "targetAsset",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "corridor",
        "type": "bytes32",
        "indexed": true,
        "internalType": "bytes32"
      },
      {
        "name": "previousRateSource",
        "type": "address",
        "indexed": false,
        "internalType": "address"
      },
      {
        "name": "rateSource",
        "type": "address",
        "indexed": false,
        "internalType": "address"
      },
      {
        "name": "previousVenue",
        "type": "address",
        "indexed": false,
        "internalType": "address"
      },
      {
        "name": "venue",
        "type": "address",
        "indexed": false,
        "internalType": "address"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "EIP712DomainChanged",
    "inputs": [],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "IntentCancelled",
    "inputs": [
      {
        "name": "intentId",
        "type": "bytes32",
        "indexed": true,
        "internalType": "bytes32"
      },
      {
        "name": "payer",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "OwnershipTransferStarted",
    "inputs": [
      {
        "name": "previousOwner",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "newOwner",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "OwnershipTransferred",
    "inputs": [
      {
        "name": "previousOwner",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "newOwner",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      }
    ],
    "anonymous": false
  },
  {
    "type": "error",
    "name": "AttestationMisbound",
    "inputs": []
  },
  {
    "type": "error",
    "name": "AuthorizationUsed",
    "inputs": [
      {
        "name": "intentId",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ]
  },
  {
    "type": "error",
    "name": "CorridorAlreadyRegistered",
    "inputs": [
      {
        "name": "sourceAsset",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "targetAsset",
        "type": "address",
        "internalType": "address"
      }
    ]
  },
  {
    "type": "error",
    "name": "CorridorNotRegistered",
    "inputs": [
      {
        "name": "sourceAsset",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "targetAsset",
        "type": "address",
        "internalType": "address"
      }
    ]
  },
  {
    "type": "error",
    "name": "InsufficientDelivery",
    "inputs": [
      {
        "name": "delivered",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "minOut",
        "type": "uint256",
        "internalType": "uint256"
      }
    ]
  },
  {
    "type": "error",
    "name": "IntentExpired",
    "inputs": [
      {
        "name": "intentId",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "deadline",
        "type": "uint64",
        "internalType": "uint64"
      }
    ]
  },
  {
    "type": "error",
    "name": "IntentNotOpen",
    "inputs": [
      {
        "name": "intentId",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "status",
        "type": "uint8",
        "internalType": "enum PayoutIntent.Status"
      }
    ]
  },
  {
    "type": "error",
    "name": "InvalidIntent",
    "inputs": [
      {
        "name": "reason",
        "type": "string",
        "internalType": "string"
      }
    ]
  },
  {
    "type": "error",
    "name": "InvalidRecipient",
    "inputs": [
      {
        "name": "recipient",
        "type": "address",
        "internalType": "address"
      }
    ]
  },
  {
    "type": "error",
    "name": "InvalidShortString",
    "inputs": []
  },
  {
    "type": "error",
    "name": "NoRoute",
    "inputs": [
      {
        "name": "assetIn",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "assetOut",
        "type": "address",
        "internalType": "address"
      }
    ]
  },
  {
    "type": "error",
    "name": "NotPayer",
    "inputs": [
      {
        "name": "caller",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "payer",
        "type": "address",
        "internalType": "address"
      }
    ]
  },
  {
    "type": "error",
    "name": "OwnableInvalidOwner",
    "inputs": [
      {
        "name": "owner",
        "type": "address",
        "internalType": "address"
      }
    ]
  },
  {
    "type": "error",
    "name": "OwnableUnauthorizedAccount",
    "inputs": [
      {
        "name": "account",
        "type": "address",
        "internalType": "address"
      }
    ]
  },
  {
    "type": "error",
    "name": "ReentrancyGuardReentrantCall",
    "inputs": []
  },
  {
    "type": "error",
    "name": "SafeERC20FailedOperation",
    "inputs": [
      {
        "name": "token",
        "type": "address",
        "internalType": "address"
      }
    ]
  },
  {
    "type": "error",
    "name": "SameAsset",
    "inputs": []
  },
  {
    "type": "error",
    "name": "SpreadTooWide",
    "inputs": [
      {
        "name": "spread",
        "type": "int256",
        "internalType": "int256"
      },
      {
        "name": "max",
        "type": "uint16",
        "internalType": "uint16"
      }
    ]
  },
  {
    "type": "error",
    "name": "StringTooLong",
    "inputs": [
      {
        "name": "str",
        "type": "string",
        "internalType": "string"
      }
    ]
  },
  {
    "type": "error",
    "name": "UnsupportedPair",
    "inputs": [
      {
        "name": "sourceAsset",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "targetAsset",
        "type": "address",
        "internalType": "address"
      }
    ]
  },
  {
    "type": "error",
    "name": "ValueOverflow",
    "inputs": []
  },
  {
    "type": "error",
    "name": "ZeroAddress",
    "inputs": []
  },
  {
    "type": "error",
    "name": "ZeroCorridor",
    "inputs": []
  }
] as const
