// GENERATED by scripts/gen-abis.mjs from contracts/out/RateAttestation.sol/RateAttestation.json — do not edit.
export const rateAttestationAbi = [
  {
    "type": "constructor",
    "inputs": [
      {
        "name": "router_",
        "type": "address",
        "internalType": "address"
      }
    ],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "attest",
    "inputs": [
      {
        "name": "intentId",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "a",
        "type": "tuple",
        "internalType": "struct IRateAttestation.Attestation",
        "components": [
          {
            "name": "corridor",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "referenceObservation",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "referenceRate",
            "type": "uint128",
            "internalType": "uint128"
          },
          {
            "name": "executedRate",
            "type": "uint128",
            "internalType": "uint128"
          },
          {
            "name": "sourceAmount",
            "type": "uint128",
            "internalType": "uint128"
          },
          {
            "name": "deliveredAmount",
            "type": "uint128",
            "internalType": "uint128"
          },
          {
            "name": "rateSource",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "spreadBps",
            "type": "int32",
            "internalType": "int32"
          },
          {
            "name": "settledAt",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "venue",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "settledAtBlock",
            "type": "uint64",
            "internalType": "uint64"
          }
        ]
      },
      {
        "name": "payer",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "recipient",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "sourceAsset",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "targetAsset",
        "type": "address",
        "internalType": "address"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "count",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "get",
    "inputs": [
      {
        "name": "intentId",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "tuple",
        "internalType": "struct IRateAttestation.Attestation",
        "components": [
          {
            "name": "corridor",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "referenceObservation",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "referenceRate",
            "type": "uint128",
            "internalType": "uint128"
          },
          {
            "name": "executedRate",
            "type": "uint128",
            "internalType": "uint128"
          },
          {
            "name": "sourceAmount",
            "type": "uint128",
            "internalType": "uint128"
          },
          {
            "name": "deliveredAmount",
            "type": "uint128",
            "internalType": "uint128"
          },
          {
            "name": "rateSource",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "spreadBps",
            "type": "int32",
            "internalType": "int32"
          },
          {
            "name": "settledAt",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "venue",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "settledAtBlock",
            "type": "uint64",
            "internalType": "uint64"
          }
        ]
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "intentIdAt",
    "inputs": [
      {
        "name": "index",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "router",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "address"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "event",
    "name": "PayoutSettled",
    "inputs": [
      {
        "name": "intentId",
        "type": "bytes32",
        "indexed": true,
        "internalType": "bytes32"
      },
      {
        "name": "corridor",
        "type": "bytes32",
        "indexed": true,
        "internalType": "bytes32"
      },
      {
        "name": "payer",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "recipient",
        "type": "address",
        "indexed": false,
        "internalType": "address"
      },
      {
        "name": "sourceAsset",
        "type": "address",
        "indexed": false,
        "internalType": "address"
      },
      {
        "name": "targetAsset",
        "type": "address",
        "indexed": false,
        "internalType": "address"
      },
      {
        "name": "a",
        "type": "tuple",
        "indexed": false,
        "internalType": "struct IRateAttestation.Attestation",
        "components": [
          {
            "name": "corridor",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "referenceObservation",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "referenceRate",
            "type": "uint128",
            "internalType": "uint128"
          },
          {
            "name": "executedRate",
            "type": "uint128",
            "internalType": "uint128"
          },
          {
            "name": "sourceAmount",
            "type": "uint128",
            "internalType": "uint128"
          },
          {
            "name": "deliveredAmount",
            "type": "uint128",
            "internalType": "uint128"
          },
          {
            "name": "rateSource",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "spreadBps",
            "type": "int32",
            "internalType": "int32"
          },
          {
            "name": "settledAt",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "venue",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "settledAtBlock",
            "type": "uint64",
            "internalType": "uint64"
          }
        ]
      }
    ],
    "anonymous": false
  },
  {
    "type": "error",
    "name": "AlreadyAttested",
    "inputs": [
      {
        "name": "intentId",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ]
  },
  {
    "type": "error",
    "name": "IndexOutOfRange",
    "inputs": [
      {
        "name": "index",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "count",
        "type": "uint256",
        "internalType": "uint256"
      }
    ]
  },
  {
    "type": "error",
    "name": "NotRouter",
    "inputs": [
      {
        "name": "caller",
        "type": "address",
        "internalType": "address"
      }
    ]
  },
  {
    "type": "error",
    "name": "ValueOverflow",
    "inputs": []
  },
  {
    "type": "error",
    "name": "ZeroAddress",
    "inputs": []
  }
] as const
