// Extracts ABIs from Foundry artifacts into packages/core/src/abi/*.ts.
// Run after `forge build`:  node scripts/gen-abis.mjs
import { readFileSync, writeFileSync, mkdirSync, existsSync } from 'node:fs'
import { join, dirname } from 'node:path'
import { fileURLToPath } from 'node:url'

const root = dirname(dirname(fileURLToPath(import.meta.url)))
const out = join(root, 'contracts', 'out')
const dest = join(root, 'packages', 'core', 'src', 'abi')
mkdirSync(dest, { recursive: true })

const contracts = [
  ['RateAttestation.sol', 'RateAttestation', 'rateAttestation'],
  ['CorridorRouter.sol', 'CorridorRouter', 'corridorRouter'],
  ['ChainlinkRateSource.sol', 'ChainlinkRateSource', 'chainlinkRateSource'],
  ['MentoVenueAdapter.sol', 'MentoVenueAdapter', 'mentoVenueAdapter'],
]

const written = []
for (const [file, name, exportName] of contracts) {
  const path = join(out, file, `${name}.json`)
  if (!existsSync(path)) {
    console.warn(`skip ${name}: ${path} not found (not compiled yet)`)
    continue
  }
  const { abi } = JSON.parse(readFileSync(path, 'utf8'))
  const ts = `// GENERATED by scripts/gen-abis.mjs from contracts/out/${file}/${name}.json — do not edit.\nexport const ${exportName}Abi = ${JSON.stringify(abi, null, 2)} as const\n`
  writeFileSync(join(dest, `${exportName}.ts`), ts)
  written.push(exportName)
}
writeFileSync(
  join(dest, 'index.ts'),
  `// GENERATED by scripts/gen-abis.mjs — do not edit.\n${written.map((n) => `export * from './${n}'`).join('\n')}\nexport * from './external'\n`,
)
console.log('wrote', written.join(', '))
